#!/bin/sh


bspc monitor -d I II III IV V VI VII VIII IX x

bspc config border_width         0
bspc config window_gap          12
bspc config border_radius       13
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config focus_follows_pointer true


# source the colors.
. "${HOME}/.cache/wal/colors.sh" &

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"


# Autorun Programs

xrdb -merge ~/.Xresources &
pkill xautolock; xautolock -time 5 -locker i3lock-fancy &
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/configs/sxhkd/sxhkdrc &
feh --bg-fill "$(< "${HOME}/.cache/wal/wal")" &
sh ~/.config/bspwm/configs/polybar/launch.sh &
pkill picom; picom --config ~/.config/bspwm/configs/picom/picom.conf --experimental-backends &
pkill redshift; redshift &
pkill libinput; libinput-gestures-setup start &
pkill dunst; dunst -conf ~/.config/bspwm/configs/dunst/dunstrc &





bspc rule -a Pavucontrol state=floating rectangle 600x500+50+50 sticky=off center=true
bspc rule -a mpv state=floating rectangle 600x400+50+50 sticky=off center=true
bspc rule -a Sxiv state=floating rectangle 600x500+50+50 sticky=off center=true
bspc rule -a Lxappearance state=floating sticky=off center=true
bspc rule -a SimpleScreenRecorder state=floating sticky=off center=true
#bspc rule -a Pcmanfm state=floating center=true rectangle 1000x650+50+50
bspc rule -a XTerm state=floating sticky=off center=true
#bspc rule -a kitty state=floating sticky=off center=true rectangle 800x500+50+50
bspc rule -a install4j-burp-StartBurp state=floating center=true
# Remove x cursor
xsetroot -cursor_name left_ptr &


bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off 

