#!/bin/bash



awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' ~/.config/bspwm/configs/sxhkd/sxhkdrc | column -t -s $'\t' | rofi -dmenu -theme ~/.config/bspwm/configs/rofi/helpmenu/helpmenu.rasi

